---
resource_types:
  - name: pivnet
    type: docker-image
    source:
      repository: pivotalcf/pivnet-resource
      tag: latest-final
resources:
  - name: platform-automation
    type: pivnet
    source:
      product_slug: platform-automation
      api_token: ((pivnet-refresh-token))
  - name: env
    type: git
    source:
      uri: https://github.com/themapisto/concourse_config.git
      branch: main
jobs:
  - name: apply-change
    serial: true
    plan:
      - get: platform-automation-image
        resource: platform-automation
        params:
          globs: ["*image*.tgz"]
          unpack: true
      - get: platform-automation-tasks
        resource: platform-automation
        params:
          globs: ["*tasks*.zip"]
          unpack: true
      - get: env
      - task: apply-changes
        image: platform-automation-image
        file: platform-automation-tasks/tasks/apply-changes.yml
        params:
          ENV_FILE: foundation/env.yml