resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: platform-automation
  type: pivnet
  source:
    product_slug: platform-automation
    api_token: ((pivnet-refresh-token))
- name: config
  type: git
  source:
    uri: https://github.com/themapisto/concourse_config.git
    branch: main
jobs:
- name: install-ops-manager
  serial: true
  plan:
    - get: platform-automation-image
      resource: platform-automation
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: config
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: concourse_client
        CREDHUB_SECRET: nladn6eysrmn3b6mbjya
        CREDHUB_SERVER: https://10.0.6.97:8844
        CREDHUB_CA_CERT: ((credhub-ca-cert))
        PREFIX: /concourse/main/
        INTERPOLATION_PATHS: foundation # contain123s download-ops-manager.yml
        SKIP_MISSING: false
      input_mapping:
        files: config
      output_mapping:
        interpolated-files: interpolated-config
    - task: download-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: foundation/download-ops-manager.yml
      input_mapping:
        config: interpolated-config
